region="ap-southeast-1"
cidr="192.168.0.0/16"
vpc_name="test_vpc_name"
sub_cidr="192.1681.0/24"
az="ap-south-1a"
subnet_name="test_subnet_name"
ig_name="test_ig_name"
route_name="test_route_table_name"
sg_name="test_sg_group"
instance_type="t2.micro"
aws_access_key="test_instance"
aws_secret_key="AKIAUVN3XXZQGTAEJ2XO"
instance_name="gia0e6Rx+b1soWBY66JHUebon00TLWiITEb0BQFi"
  
